---
title: Interested in Joining the Lab?
page-layout: full
---

Thank you for your interest- please see the information below for a potential position that applies to you!

### **Graduate Students:**

Dr. Turner is able to take on graduate students through the Neuroscience Graduate Program. Please email Dr. Turner to see if she is taking any students for the current application cycle. Potential applicants should have an interest in neuroimaging related to various psychiatric disorders.

### **Undergraduate Research Assistant:**

Volunteer researchers in the Turner lab can come from any undergraduate major, but a more quantitative background is better for data analysis projects. Research assistants are expected to have some interest in investigating and learning about what they don't already know, and should be prepared to do regular background reading on their own as part of their responsibilities.  Having had some statistics, math, or computer science classes, or psychology, biology or neuroscience classes, is desirable but not required. A respectable GPA is definitely desirable. 

Volunteer researchers are expected to put in 8-10 hours a week and commit to at least two semesters; responsibilities will vary depending on the research project, but the goal is always to find a fit between the needs of the projects and the career development goals of those working on the project. Lab members are expected to attend the weekly lab meetings (Fridays at 11 am; Teams link available) and to present about their project at the lab meeting at least once a year. 

The research projects that are available change regularly; there are both data collection and data analysis projects underway. All projects require responsible and reliable research personnel. 

If you are interested in research opportunities with the Turner lab, please drop us an email with a paragraph explaining your background and interests, and if space in the lab is available, we will set up a meeting to discuss possibilities.  Sitting in on the lab meetings to hear the presentations is also an option.

### **Post-baccalaureate Research Assistant:**

Interested applicants for the ARTEMIS Study should email Dr. Turner to inquire if there are any open positions.
